-- INSERT INTO `DEPARTMENT` (name, reg_nm, modi_nm) VALUES ('Đa khoa', 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Phỏng đoán và chẩn đoán hình ảnh', 'administrator', 'administrator');
INSERT INTO `department_symptom_mapping` (department_id, symptom_id, `reg_nm`, `modi_nm`) VALUES ((SELECT ID FROM DEPARTMENT WHERE name='Đa khoa'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Khám và tư vấn bệnh nghề nghiệp', 'administrator', 'administrator');
INSERT INTO `department_symptom_mapping` (department_id, symptom_id, `reg_nm`, `modi_nm`) VALUES ((SELECT ID FROM DEPARTMENT WHERE name='Đa khoa'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Khám và điều trị bệnh Nội khoa', 'administrator', 'administrator');
INSERT INTO `department_symptom_mapping` (department_id, symptom_id, `reg_nm`, `modi_nm`) VALUES ((SELECT ID FROM DEPARTMENT WHERE name='Đa khoa'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Chữa nhiều bệnh khó về Sản khoa', 'administrator', 'administrator');
INSERT INTO `department_symptom_mapping` (department_id, symptom_id, `reg_nm`, `modi_nm`) VALUES ((SELECT ID FROM DEPARTMENT WHERE name='Đa khoa'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Chữa bệnh kết hợp với các phương pháp y học phương đông và cổ truyền', 'administrator', 'administrator');
INSERT INTO `department_symptom_mapping` (department_id, symptom_id, `reg_nm`, `modi_nm`) VALUES ((SELECT ID FROM DEPARTMENT WHERE name='Đa khoa'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Thực hiện các thủ thuật can thiệp', 'administrator', 'administrator');
INSERT INTO `department_symptom_mapping` (department_id, symptom_id, `reg_nm`, `modi_nm`) VALUES ((SELECT ID FROM DEPARTMENT WHERE name='Đa khoa'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Giáo dục và tư vấn sức khỏe', 'administrator', 'administrator');
INSERT INTO `department_symptom_mapping` (department_id, symptom_id, `reg_nm`, `modi_nm`) VALUES ((SELECT ID FROM DEPARTMENT WHERE name='Đa khoa'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị bệnh viêm hô hấp mãn tính trẻ em', 'administrator', 'administrator');
INSERT INTO `department_symptom_mapping` (department_id, symptom_id, `reg_nm`, `modi_nm`) VALUES ((SELECT ID FROM DEPARTMENT WHERE name='Đa khoa'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Chữa ốm ho hay viêm phế quản trẻ em tái phát nhiều lần ', 'administrator', 'administrator');
INSERT INTO `department_symptom_mapping` (department_id, symptom_id, `reg_nm`, `modi_nm`) VALUES ((SELECT ID FROM DEPARTMENT WHERE name='Đa khoa'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điệu trị bệnh lý đau mãn tình như đau đầu lâu ngày', 'administrator', 'administrator');
INSERT INTO `department_symptom_mapping` (department_id, symptom_id, `reg_nm`, `modi_nm`) VALUES ((SELECT ID FROM DEPARTMENT WHERE name='Đa khoa'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị đau vai gáy', 'administrator', 'administrator');
INSERT INTO `department_symptom_mapping` (department_id, symptom_id, `reg_nm`, `modi_nm`) VALUES ((SELECT ID FROM DEPARTMENT WHERE name='Đa khoa'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị đau tê chân tay', 'administrator', 'administrator');
INSERT INTO `department_symptom_mapping` (department_id, symptom_id, `reg_nm`, `modi_nm`) VALUES ((SELECT ID FROM DEPARTMENT WHERE name='Đa khoa'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị đau nửa đầu', 'administrator', 'administrator');
INSERT INTO `department_symptom_mapping` (department_id, symptom_id, `reg_nm`, `modi_nm`) VALUES ((SELECT ID FROM DEPARTMENT WHERE name='Đa khoa'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị chóng mặt', 'administrator', 'administrator');
INSERT INTO `department_symptom_mapping` (department_id, symptom_id, `reg_nm`, `modi_nm`) VALUES ((SELECT ID FROM DEPARTMENT WHERE name='Đa khoa'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị bệnh thần kinh tọa', 'administrator', 'administrator');
INSERT INTO `department_symptom_mapping` (department_id, symptom_id, `reg_nm`, `modi_nm`) VALUES ((SELECT ID FROM DEPARTMENT WHERE name='Đa khoa'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị thoát vị đĩa đệm', 'administrator', 'administrator');
INSERT INTO `department_symptom_mapping` (department_id, symptom_id, `reg_nm`, `modi_nm`) VALUES ((SELECT ID FROM DEPARTMENT WHERE name='Đa khoa'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị thoái hóa đốt sống lưng bằng phương pháp thông kinh lạc', 'administrator', 'administrator');
INSERT INTO `department_symptom_mapping` (department_id, symptom_id, `reg_nm`, `modi_nm`) VALUES ((SELECT ID FROM DEPARTMENT WHERE name='Đa khoa'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị run tay chân', 'administrator', 'administrator');
INSERT INTO `department_symptom_mapping` (department_id, symptom_id, `reg_nm`, `modi_nm`) VALUES ((SELECT ID FROM DEPARTMENT WHERE name='Đa khoa'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị nháy mắt', 'administrator', 'administrator');
INSERT INTO `department_symptom_mapping` (department_id, symptom_id, `reg_nm`, `modi_nm`) VALUES ((SELECT ID FROM DEPARTMENT WHERE name='Đa khoa'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị co giật cơ', 'administrator', 'administrator');
INSERT INTO `department_symptom_mapping` (department_id, symptom_id, `reg_nm`, `modi_nm`) VALUES ((SELECT ID FROM DEPARTMENT WHERE name='Đa khoa'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị bệnh Parkinson', 'administrator', 'administrator');
INSERT INTO `department_symptom_mapping` (department_id, symptom_id, `reg_nm`, `modi_nm`) VALUES ((SELECT ID FROM DEPARTMENT WHERE name='Đa khoa'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị hôi miệng', 'administrator', 'administrator');
INSERT INTO `department_symptom_mapping` (department_id, symptom_id, `reg_nm`, `modi_nm`) VALUES ((SELECT ID FROM DEPARTMENT WHERE name='Đa khoa'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị miệng khô, rêu lưỡi dày', 'administrator', 'administrator');
INSERT INTO `department_symptom_mapping` (department_id, symptom_id, `reg_nm`, `modi_nm`) VALUES ((SELECT ID FROM DEPARTMENT WHERE name='Đa khoa'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị mất ngủ', 'administrator', 'administrator');
INSERT INTO `department_symptom_mapping` (department_id, symptom_id, `reg_nm`, `modi_nm`) VALUES ((SELECT ID FROM DEPARTMENT WHERE name='Đa khoa'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị rối loạn thần kinh thực vật', 'administrator', 'administrator');
INSERT INTO `department_symptom_mapping` (department_id, symptom_id, `reg_nm`, `modi_nm`) VALUES ((SELECT ID FROM DEPARTMENT WHERE name='Đa khoa'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị trầm cảm', 'administrator', 'administrator');
INSERT INTO `department_symptom_mapping` (department_id, symptom_id, `reg_nm`, `modi_nm`) VALUES ((SELECT ID FROM DEPARTMENT WHERE name='Đa khoa'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị rối loạn tâm thần kinh', 'administrator', 'administrator');
INSERT INTO `department_symptom_mapping` (department_id, symptom_id, `reg_nm`, `modi_nm`) VALUES ((SELECT ID FROM DEPARTMENT WHERE name='Đa khoa'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị xuất huyết dạ dày tái đi tái lại nhiều lần', 'administrator', 'administrator');
INSERT INTO `department_symptom_mapping` (department_id, symptom_id, `reg_nm`, `modi_nm`) VALUES ((SELECT ID FROM DEPARTMENT WHERE name='Đa khoa'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị hội chứng ruột kích thích hay tiêu chảy, tiêu chảy sau ăn', 'administrator', 'administrator');
INSERT INTO `department_symptom_mapping` (department_id, symptom_id, `reg_nm`, `modi_nm`) VALUES ((SELECT ID FROM DEPARTMENT WHERE name='Đa khoa'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Ổn định đường huyết trong bệnh tiểu đường', 'administrator', 'administrator');
INSERT INTO `department_symptom_mapping` (department_id, symptom_id, `reg_nm`, `modi_nm`) VALUES ((SELECT ID FROM DEPARTMENT WHERE name='Đa khoa'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị các biến chứng của bệnh tiểu đường', 'administrator', 'administrator');
INSERT INTO `department_symptom_mapping` (department_id, symptom_id, `reg_nm`, `modi_nm`) VALUES ((SELECT ID FROM DEPARTMENT WHERE name='Đa khoa'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị bệnh lậu', 'administrator', 'administrator');
INSERT INTO `department_symptom_mapping` (department_id, symptom_id, `reg_nm`, `modi_nm`) VALUES ((SELECT ID FROM DEPARTMENT WHERE name='Đa khoa'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị viêm niệu đạo mãn tính', 'administrator', 'administrator');
INSERT INTO `department_symptom_mapping` (department_id, symptom_id, `reg_nm`, `modi_nm`) VALUES ((SELECT ID FROM DEPARTMENT WHERE name='Đa khoa'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị mày đay mãn tính', 'administrator', 'administrator');
INSERT INTO `department_symptom_mapping` (department_id, symptom_id, `reg_nm`, `modi_nm`) VALUES ((SELECT ID FROM DEPARTMENT WHERE name='Đa khoa'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị ngứa mãn tính', 'administrator', 'administrator');
INSERT INTO `department_symptom_mapping` (department_id, symptom_id, `reg_nm`, `modi_nm`) VALUES ((SELECT ID FROM DEPARTMENT WHERE name='Đa khoa'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị vẩy phấn hồng', 'administrator', 'administrator');
INSERT INTO `department_symptom_mapping` (department_id, symptom_id, `reg_nm`, `modi_nm`) VALUES ((SELECT ID FROM DEPARTMENT WHERE name='Đa khoa'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị luput ban đỏ', 'administrator', 'administrator');
INSERT INTO `department_symptom_mapping` (department_id, symptom_id, `reg_nm`, `modi_nm`) VALUES ((SELECT ID FROM DEPARTMENT WHERE name='Đa khoa'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị vẩy nến đã điều trị đông tây y nhiều nơi chưa khỏi', 'administrator', 'administrator');
INSERT INTO `department_symptom_mapping` (department_id, symptom_id, `reg_nm`, `modi_nm`) VALUES ((SELECT ID FROM DEPARTMENT WHERE name='Đa khoa'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị bệnh ung thư các thể loại ', 'administrator', 'administrator');
INSERT INTO `department_symptom_mapping` (department_id, symptom_id, `reg_nm`, `modi_nm`) VALUES ((SELECT ID FROM DEPARTMENT WHERE name='Đa khoa'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Tư vấn tâm lý', 'administrator', 'administrator');
INSERT INTO `department_symptom_mapping` (department_id, symptom_id, `reg_nm`, `modi_nm`) VALUES ((SELECT ID FROM DEPARTMENT WHERE name='Đa khoa'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Tư vấn chữa bệnh bằng đông, tây Y và dinh dưỡng học người Nga Tăng cường miễn dịch trẻ em', 'administrator', 'administrator');
INSERT INTO `department_symptom_mapping` (department_id, symptom_id, `reg_nm`, `modi_nm`) VALUES ((SELECT ID FROM DEPARTMENT WHERE name='Đa khoa'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Tư vấn giảm cân', 'administrator', 'administrator');
INSERT INTO `department_symptom_mapping` (department_id, symptom_id, `reg_nm`, `modi_nm`) VALUES ((SELECT ID FROM DEPARTMENT WHERE name='Đa khoa'), LAST_INSERT_ID(), 'administrator', 'administrator');
