-- INSERT INTO `DEPARTMENT` (name, reg_nm, modi_nm) VALUES ('Dị ứng miễn dịch', 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị hen', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Dị ứng miễn dịch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị các bệnh dị ứng tự miễn', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Dị ứng miễn dịch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Trị bệnh dị ứng thuốc', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Dị ứng miễn dịch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Trị bệnh dị ứng hoá chất', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Dị ứng miễn dịch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Trị bệnh dị ứng mỹ phẩm', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Dị ứng miễn dịch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Trị bệnh dị ứng thức ăn', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Dị ứng miễn dịch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Trị hen phế quản', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Dị ứng miễn dịch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Trị viêm mũi xoang dị ứng', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Dị ứng miễn dịch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Trị viêm kết mạc dị ứng', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Dị ứng miễn dịch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Trị chàm', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Dị ứng miễn dịch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Trị mày đay mạn tính', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Dị ứng miễn dịch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Trị luput ban đỏ hệ thống', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Dị ứng miễn dịch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Trị xơ cứng bì hệ thống', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Dị ứng miễn dịch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Trị viêm da cơ', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Dị ứng miễn dịch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Trị viêm mạch hệ thống', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Dị ứng miễn dịch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Trị viêm gan tự miễn', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Dị ứng miễn dịch'), LAST_INSERT_ID(), 'administrator', 'administrator');
