-- INSERT INTO `DEPARTMENT` (name, reg_nm, modi_nm) VALUES ('Hô hấp', 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Khám và điều trị các bệnh lý về Hô Hấp', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Hô hấp'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Chữa các bệnh về họng', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Hô hấp'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Chữa các bệnh về hô hấp', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Hô hấp'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Chữa viêm phế quản', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Hô hấp'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Nhận khám bệnh', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Hô hấp'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Chữa các bệnh về hô hấp', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Hô hấp'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Chữa viêm phế quản', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Hô hấp'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Chữa hen phế quản', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Hô hấp'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị lao', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Hô hấp'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị các bệnh phổi', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Hô hấp'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị bệnh lý hô hấp', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Hô hấp'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị bệnh hô hấp ở trẻ em', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Hô hấp'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị ung thư phổi', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Hô hấp'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị suyễn và bệnh phổi tắc nghẽn mãn tính', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Hô hấp'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị nhiễm trực khuẩn Mycobacteria bao gồm vi khuẩn lao', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Hô hấp'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị bệnh về mũi cho trẻ', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Hô hấp'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị bệnh về họng cho trẻ', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Hô hấp'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị bệnh về thanh quản cho trẻ', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Hô hấp'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị bệnh về khí phế quản cho trẻ', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Hô hấp'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị bệnh về phổi cho trẻ', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Hô hấp'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị bệnh về màng phổi cho trẻ', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Hô hấp'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị bệnh về lồng ngực cho trẻ', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Hô hấp'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị bệnh về các cơ hô hấp cho trẻ', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Hô hấp'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị viêm phế quản phổi', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Hô hấp'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị viêm thanh khí phế quản', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Hô hấp'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị hen phế quản', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Hô hấp'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị dãn phế quản', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Hô hấp'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Lấy dị vật đường thở', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Hô hấp'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị tràn mủ', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Hô hấp'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị tràn khí màng phổi', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Hô hấp'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị lao sơ nhiễm', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Hô hấp'), LAST_INSERT_ID(), 'administrator', 'administrator');
