-- INSERT INTO `DEPARTMENT` (name, reg_nm, modi_nm) VALUES ('Tai mũi họng', 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Khám chữa bệnh tai - mũi - họng', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Khám chữa bệnh tai mũi họng người lớn', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Khám chữa bệnh tai mũi họng trẻ em', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị viêm thanh quản cấp, mạn', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị chảy mủ tai', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị viêm tai giữa màng nhĩ đóng kín', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị viêm tai giữa cấp, mạn', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Phẫu thuật chữa điếc', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị điếc đột ngột', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị nghe kém', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị có đờm mạn tính ở họng', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị polyp thanh quản, hạt xơ dây thanh', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị viêm mũi ngạt tắc mũi mạn tính', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị viêm mũi vận mạch', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị những trường hợp ngủ dậy miệng đắng', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị hơi thở hôi', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị đau đầu mãn tính do mũi xoang', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị viêm mũi xoang dị ứng', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị nấm mũi xoang', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị ù tai', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị viêm đa xoang mạn lâu ngày khó khỏi', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị viêm họng hạt', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị polyp mũi xoang', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị vá màng nhĩ nội soi', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Khám Tai Mũi Họng', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị phẫu thuật thay thế xương con', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị ù tai', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị nghe kém', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị điếc đột ngột', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Phẫu thuật chữa điếc', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị chẩy mủ tai', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị viêm tai giữa cấp tính', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị viêm tai giữa mãn tính', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị phẫu thuật thay thế xương con', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị vá màng nhĩ nội soi', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị viêm tai giữa màng nhĩ đóng kín', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Phẫu thuật các khối u vùng tai', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị viêm mũi xoang dị ứng', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị viêm mũi vận mạch', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị viêm mũi ngạt tắc mũi mãn tính', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị cuốn mũi quá phát', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị dị hình mũi vẹo vách ngăn', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị dị hình mũi gai vách ngăn', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị dị hình mũi gờ vách ngăn', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị viêm đa xoang mạn lâu ngày khó khỏi', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị polyp mũi xoang', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị nấm mũi xoang', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Khôi u mũi xoang', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị đau đầu mãn tính do mũi xoang', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị viêm thanh quản cấp tính', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị viêm thanh quản mãn tính', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị polyp thanh quản', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị hạt xơ dây thanh', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị U nang dây thanh', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị các khối u hạ họng tanh quản', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị viêm họng hạt', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị viêm VA ', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị viêm amidan ', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị ngủ ngáy do cuốn mũi', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị ngủ ngáy do vách ngăn', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị ngủ ngáy do anidan', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị ngủ ngáy do màn hầu lưỡi gà quá phát', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị những trường hợp ngủ dậy miệng đắng', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị hơi thở hôi', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị có đờm mãn tính ở họng', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Bệnh trào ngược dạ dày thực quản ', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Nâng mũi', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị vệnh viêm họng', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị viêm amidan', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Châm cứu', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Day ấn huyệt', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Cứu ngải', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Giác hơi', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Khám chữa các bệnh về tai', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Khám chữa bệnh về họng', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Khám chữa bệnh về mũi', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Tư vấn và điều trị viêm thanh quản- khàn tiếng', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Khám phát hiện sớm ung thư vòm', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Khám phát hiện sớm ung thư thanh quản', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Khám phát hiện sớm ung thư mũi xoang', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Khám phát hiện sớm ung thư hạ họng', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Tư vấn và điều trị viêm phế quản', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Khám chữa các bệnh về tai', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Khám chữa bệnh về mũi', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Khám chữa bệnh về họng ', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị viêm thanh quản', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị bệnh khàn tiếng', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị viêm phế quản', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Khám phát hiện sớm ung thư vòm', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Khám phát hiện sớm ung thư thanh quản', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Khám phát hiện sớm ung thư mũi xoang', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Khám phát hiện sớm ung thư hạ họng', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Chữa cơ xương khớp', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị các bệnh nội hô hấp', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị các bệnh về Tai - Mũi - Họng Người lớn & Trẻ em', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Bán kính thuốc, kính thời trang, kính áp tròng', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tai mũi họng'), LAST_INSERT_ID(), 'administrator', 'administrator');
