-- INSERT INTO department (name, reg_nm, modi_nm) VALUES ('Tim mạch', 'administrator', 'administrator');
INSERT INTO symptom (name, reg_nm, modi_nm) VALUES ('Khám', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM department WHERE name='Tim mạch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO symptom (name, reg_nm, modi_nm) VALUES ('Điều trị nội', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM department WHERE name='Tim mạch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO symptom (name, reg_nm, modi_nm) VALUES ('Điều trị các bệnh nội tim mạch', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM department WHERE name='Tim mạch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO symptom (name, reg_nm, modi_nm) VALUES ('Điều trị các bệnh nội thận', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM department WHERE name='Tim mạch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO symptom (name, reg_nm, modi_nm) VALUES ('Điều trị các bệnh nội cơ xương khớp', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM department WHERE name='Tim mạch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO symptom (name, reg_nm, modi_nm) VALUES ('Điều trị các bệnh nội tiết', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM department WHERE name='Tim mạch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO symptom (name, reg_nm, modi_nm) VALUES ('Phục hồi chức năng', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM department WHERE name='Tim mạch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO symptom (name, reg_nm, modi_nm) VALUES ('Phẫu thuật tim mạch', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM department WHERE name='Tim mạch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO symptom (name, reg_nm, modi_nm) VALUES ('Phẫu thuật tim bẩm sinh', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM department WHERE name='Tim mạch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO symptom (name, reg_nm, modi_nm) VALUES ('Phẫu thuật thông liên nhĩ', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM department WHERE name='Tim mạch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO symptom (name, reg_nm, modi_nm) VALUES ('Phẫu thuật thông liên thất', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM department WHERE name='Tim mạch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO symptom (name, reg_nm, modi_nm) VALUES ('Phẫu thuật tứ chứng fallot', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM department WHERE name='Tim mạch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO symptom (name, reg_nm, modi_nm) VALUES ('Phẫu thuật thông sàn nhĩ thất', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM department WHERE name='Tim mạch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO symptom (name, reg_nm, modi_nm) VALUES ('Phẫu thuật tim một thất', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM department WHERE name='Tim mạch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO symptom (name, reg_nm, modi_nm) VALUES ('Thay hoặc sửa van hai lá', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM department WHERE name='Tim mạch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO symptom (name, reg_nm, modi_nm) VALUES ('Thay van động mạch chủ', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM department WHERE name='Tim mạch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO symptom (name, reg_nm, modi_nm) VALUES ('Chữa cơ xương khớp', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM department WHERE name='Tim mạch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO symptom (name, reg_nm, modi_nm) VALUES ('Điều trị các bệnh về Nội Tiêu hóa', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM department WHERE name='Tim mạch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO symptom (name, reg_nm, modi_nm) VALUES ('Khám và điều trị các bệnh Nội Tim mạch', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM department WHERE name='Tim mạch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO symptom (name, reg_nm, modi_nm) VALUES ('Khám và điều trị các bệnh Nội Hô hấp', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM department WHERE name='Tim mạch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO symptom (name, reg_nm, modi_nm) VALUES ('Điều trị các bệnh nội tiêu hóa', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM department WHERE name='Tim mạch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO symptom (name, reg_nm, modi_nm) VALUES ('Điều trị các bệnh nội tim mạch', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM department WHERE name='Tim mạch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO symptom (name, reg_nm, modi_nm) VALUES ('Điều trị các bệnh nội hô hấp', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM department WHERE name='Tim mạch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO symptom (name, reg_nm, modi_nm) VALUES ('Điều trị các bệnh truyền nhiễm', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM department WHERE name='Tim mạch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO symptom (name, reg_nm, modi_nm) VALUES ('Điều trị bệnh lý van tim', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM department WHERE name='Tim mạch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO symptom (name, reg_nm, modi_nm) VALUES ('Điều trị bệnh động mạch vành', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM department WHERE name='Tim mạch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO symptom (name, reg_nm, modi_nm) VALUES ('Điều trị bệnh cơ tim', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM department WHERE name='Tim mạch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO symptom (name, reg_nm, modi_nm) VALUES ('Điều trị rối loạn nhịp tim', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM department WHERE name='Tim mạch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO symptom (name, reg_nm, modi_nm) VALUES ('Điều trị suy tim', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM department WHERE name='Tim mạch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO symptom (name, reg_nm, modi_nm) VALUES ('Điều trị viêm tắc động tĩnh mạch', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM department WHERE name='Tim mạch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO symptom (name, reg_nm, modi_nm) VALUES ('Điều trị tăng huyết áp', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM department WHERE name='Tim mạch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO symptom (name, reg_nm, modi_nm) VALUES ('Tư vấn phòng ngừa bệnh tim mạch', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM department WHERE name='Tim mạch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO symptom (name, reg_nm, modi_nm) VALUES ('Chữa bệnh đột quỵ', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM department WHERE name='Tim mạch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO symptom (name, reg_nm, modi_nm) VALUES ('Chữa bệnh tim mạch', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM department WHERE name='Tim mạch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO symptom (name, reg_nm, modi_nm) VALUES ('Chữa bệnh ung thư', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM department WHERE name='Tim mạch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO symptom (name, reg_nm, modi_nm) VALUES ('Chữa bệnh bằng y học cổ truyền', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM department WHERE name='Tim mạch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO symptom (name, reg_nm, modi_nm) VALUES ('Điều trị bệnh đột quỵ', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM department WHERE name='Tim mạch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO symptom (name, reg_nm, modi_nm) VALUES ('Chữa bệnh lý liệt do tai biến mạch máu não', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM department WHERE name='Tim mạch'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO symptom (name, reg_nm, modi_nm) VALUES ('Giảm đau', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM department WHERE name='Tim mạch'), LAST_INSERT_ID(), 'administrator', 'administrator');
