INSERT INTO `DEPARTMENT` (name, reg_nm, modi_nm) VALUES ('Tiêu hoá gan mật', 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Chữa trào ngược dạ dày, thực quản', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Chữa ung thư gan', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Chữa viêm đại tràng', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Chữa viêm gan B', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Chữa viêm gan C', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Khám viêm gan', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Chữa bệnh hội chứng ruột kích thích', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Chữa viêm dạ dày', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Chữa bệnh xơ gan', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị viêm dạ dày', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị bệnh trào ngược dạ dày thực quản', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị viêm đại tràng', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị rối loạn tiêu hóa', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị hội chứng ruột kích thích', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị rối loạn hệ vi sinh đường ruột', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị viêm gan', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị xơ gan', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Tư vấn điều trị ung thư gan', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Phẫu thuật nội soi Tiêu hóa - Gan mật', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Khám điều trị bệnh áp-xe cạnh hậu môn', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Chữa tiêu hóa', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Khám tiêu hóa', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Khám về tiêu hóa', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Phẫu thuật trực tràng', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị bệnh trĩ, trĩ nội, trĩ ngoại', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Phẫu thuật rò hậu môn', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị hậu môn', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Phẫu thuật bướu cổ', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị bệnh sỏi tiết niệu', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Cấp cứu tiêu hóa', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Khám, tư vấn và Phẫu thuật trĩ', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Khám và điều trị Áp xe - Rò hậu môn', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Khám và điều trị Polype hậu môn', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Khám và điều trị Các bệnh lý khác vùng hậu môn trực tràng.Khám và điều trị các bệnh tiêu hóa, gan mật.', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Khám và điều trị các bệnh lý thận - tiết niệu', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Khám và điều trị các bệnh chấn thương xương khớp', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Các bệnh Ngoại khoa khác', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Phẫu thuật nội soi', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Chữa bệnh đại tràng', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Chữa bệnh gan mật', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Chữa trĩ', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Chữa đau dạ dày', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Chữa bệnh gan mật', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Chữa bệnh đại tràng', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Chữa trĩ', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Chữa đái dầm', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị bệnh thực quản', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị bệnh dạ dày', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị bệnh đại tràng', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị rối loạn tiêu hóa', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
INSERT INTO `SYMPTOM` (name, reg_nm, modi_nm) VALUES ('Điều trị xuất huyết tiêu hóa', 'administrator', 'administrator');
INSERT INTO department_symptom_mapping (department_id, symptom_id, reg_nm, modi_nm) VALUES ((SELECT ID FROM DEPARTMENT WHERE `NAME`='Tiêu hoá gan mật'), LAST_INSERT_ID(), 'administrator', 'administrator');
